### PR TITLE
fix EnvList.Set override

### PR DESCRIPTION
**Pull request by littlexiang**
currently SUP_TIME override is not working due to this bug

### CODE REVIEW

**Comment by VojtechVitek** [comment]
Thanks for your contribution, @littlexiang!

**Comment by littlexiang** [comment]
Many thx to you guys for the job.
I've built our deploy webhook console over Sup and it works great for all kinds of langs (php/go/node/java)

**Comment by VojtechVitek** [comment]
@littlexiang sounds interesting! I'd be interested in more details / screenshot of the console :)

**Comment by littlexiang** [comment]
it's a simple tool works with our private gitlab
what it's doing is to accept webhook callbak and match some particular branch/version/comment, then triggers shell exec with Sup/Bash/Fabric/PM2 etc 
so we can keep Supfile within the project itself and
 it's quite convenient for devops

1 pic
18 pic_hd
19 pic_hd
111 pic_hd

**Pull request merged**
