### PR TITLE
Implement passing env vars via CLI --env flag

### LINKED ISSUE #46: Pass extra env from command line
Is there a way that I do something like this?
```sup --env BACKUP_DIR=/path/to/dir production rollback```

### PR DESCRIPTION
**Pull request by VojtechVitek**
Fixes #46

### CODE REVIEW

**Comment by eduardonunesp** [comment]
How to declares multiple variables ? Could create a sample ?

**Comment by VojtechVitek** [comment]
@eduardonunesp same as docker:
`sup -e first=value -e second=value production deploy`

**Comment by VojtechVitek** [comment]
In fact, I'm working on `$SUP_ENV` variable, which you can pass to Docker cmds or nested `sup -f ...`

**Comment by eduardonunesp** [comment]
is it stable ?

**Comment by VojtechVitek** [comment]
@AmitKumarDas yes, this is correct usage.

Let me merge this, since I can do $SUP_ENV separately.

**Comment by AmitKumarDas** [comment]
Thanks a lot @VojtechVitek

**Pull request merged**
