### PR TITLE
fix problem with race conditions #24

### PR DESCRIPTION
**Pull request by lexa-uw**

### CODE REVIEW

**Comment by VojtechVitek** [comment]
This looks good. Let me test it first and I'm gonna merge it. Thanks!

**Comment by eduardonunesp** [comment]
Looking forward for that fix

**Comment by VojtechVitek** [comment]
Unfortunatelly, this PR breaks input and output streaming.

**Comment by eduardonunesp** [comment]
That is sad, we need to figure out how to use timers resolve that race

**Comment by lexa-uw** [comment]
This cases I did not test, sorry.

>> to use timers resolve that race

I agree.

**Comment by VojtechVitek** [comment]
Let's continue at #36

**Pull request closed without merging**
